version: "3.3"
services:
  backend:
    container_name: backend
    build: ./backend
    env_file: .env
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - redis1
      - redis2
      - redis3
    environment:
      FLASK_ENV: development

  client:
    container_name: client
    build: ./client
    ports:
      - "8000:5000"
    depends_on:
      - backend
      - postgres
      - redis1
      - redis2
      - redis3

  postgres:
    image: postgres:latest
    container_name: pgSD
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USER=${POSTGRES_USER}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - ALLOW_EMPTY_PASSWORD=${HIDE_EMPTY_PASSWORD}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}

  redis1:
    image: redis:6.2.6
    container_name: redis-TareaSD-1
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always

  redis2:
    image: redis:6.2.6
    container_name: redis-TareaSD-2
    ports:
      - "6380:6380"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always

  redis3:
    image: redis:6.2.6
    container_name: redis-TareaSD-3
    ports:
      - "6381:6381"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
