version: '3.3'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - '50051:50051'
    depends_on:
      - postgres
      - redis1
      - redis2
      - redis3

  client:
    container_name: client
    build: ./client
    ports:
      - '8000:8000'
    depends_on:
      - backend
      - postgres
      - redis1
      - redis2
      - redis3

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_DB: POSTGRES_DB

  redis1:
    image: bitnami/redis:latest
    container_name: redis-TareaSD-1
    ports:
      - "6370:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    
  redis2:
    image: bitnami/redis:latest
    container_name: redis-TareaSD-2
    ports:
      - "7777:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    
  redis3:
    image: bitnami/redis:latest
    container_name: redis-TareaSD-3
    ports:
      - "7002:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
